services:
  - type: web
    name: pi-barbearia
    env: python
    plan: free
    buildCommand: pip install -r requirements/prod.txt && python manage.py collectstatic --noinput
    preDeployCommand: python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
