# Generated by Django 6.0.4 on 2026-05-02 01:08

import apps.clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("clientes", "0003_data_migration"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="clienteuser",
            managers=[
                ("objects", apps.clientes.models.ClienteUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="clienteuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="clienteuser",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
    ]
