# Generated by Django 6.0.4 on 2026-04-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agendamento',
            new_name='agendamento_data_ho_636114_idx',
            old_name='agendamento_data_ho_idx',
        ),
        migrations.RenameIndex(
            model_name='agendamento',
            new_name='agendamento_status_f1d4ee_idx',
            old_name='agendamento_status_idx',
        ),
        migrations.RenameIndex(
            model_name='agendamento',
            new_name='agendamento_profiss_cd22d6_idx',
            old_name='agendamento_profiss_idx',
        ),
    ]
