# Generated by Django 6.0.4 on 2026-05-02 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "agendamentos",
            "0002_rename_agendamento_data_ho_idx_agendamento_data_ho_636114_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenConfirmacaoAgendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("usado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "acao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CONFIRMADO", "Confirmado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "agendamento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_confirmacao",
                        to="agendamentos.agendamento",
                    ),
                ),
            ],
            options={
                "db_table": "token_confirmacao_agendamento",
            },
        ),
    ]
