# Generated by Django

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lunch_start', models.TimeField(blank=True, null=True)),
                ('lunch_end', models.TimeField(blank=True, null=True)),
                ('is_day_off', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='profissionais.profissional')),
            ],
            options={
                'db_table': 'professional_schedule',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='professionalschedule',
            index=models.Index(fields=['profissional', 'weekday'], name='profissiona_professi_weekd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='professionalschedule',
            unique_together={('profissional', 'weekday')},
        ),
    ]
