# Generated by Django 6.0.4 on 2026-05-02 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profissionais", "0002_professionalschedule"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="professionalschedule",
            new_name="professiona_profiss_b1bbab_idx",
            old_name="profissiona_professi_weekd_idx",
        ),
    ]
