# Generated by Django 6.0.4 on 2026-04-25 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '0002_rename_agendamento_data_ho_idx_agendamento_data_ho_636114_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONFIRMACAO_SOLICITADA', 'Solicitação de Confirmação'), ('LEMBRETE_DIA', 'Lembrete do Dia')], max_length=30)),
                ('destinatario', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('ENVIADO', 'Enviado'), ('FALHOU', 'Falhou')], max_length=10)),
                ('erro', models.TextField(blank=True, default='')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='agendamentos.agendamento')),
            ],
            options={
                'verbose_name': 'Log de Notificação',
                'verbose_name_plural': 'Logs de Notificações',
                'db_table': 'notificacao_log',
                'ordering': ['-enviado_em'],
            },
        ),
    ]
