# Generated by Django 6.0.4 on 2026-05-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0002_notificacaolog_provider_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacaolog",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("CONFIRMACAO_SOLICITADA", "Solicitação de Confirmação"),
                    ("LEMBRETE_DIA", "Lembrete do Dia"),
                    ("LEMBRETE_COM_LINK", "Lembrete com Link de Confirmação"),
                ],
                max_length=30,
            ),
        ),
    ]
